#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

#include "args.h"  // generated by genargs

int main(int argc, char** argv) {
    Args a; memset(&a, 0, sizeof(a));
    int rc = parse_args(argc, argv, &a, NULL); // prog_name comes from generated code default
    if (rc != 0) {
        fprintf(stderr, "Failed to parse arguments (rc=%d)\n", rc);
        print_usage(NULL);
        return 1;
    }

    printf("Parsed arguments:\n");

    // For -j (int)
    if (a.has_j) {
        printf("  -j: %d\n", a.j);
    } else {
        printf("  -j: (not set)\n");
    }

    // For -f (bool)
    printf("  -f: %s\n", a.f ? "true" : "false");

    // For -w (string)
    if (a.has_w && a.w) {
        printf("  -w: %s\n", a.w);
    } else {
        printf("  -w: (not set)\n");
    }

    free_args(&a);
    return 0;
}
