/ 1 Define a lambda function that takes two numbers and subtracts 1 from their sum.
{-1+x+y}[1;2]
{x+y-1}[1;2]

/ 2 Define a train which has the same function as the one from Question 1.
(-1++)[3;4]

/ 3 Create the array (1 2 3;4 5 6) with the help of the verbs you learned in the previous chapter. Then, make a dictionary with the first row as keys, and the second row as values.
{(3#x)!(3_x)}[1+!6]
!/0 3_1+!6
